// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Object.EntityFrameworkCore.DbMigrations;
using Volo.Abp.EntityFrameworkCore;

namespace Object.EntityFrameworkCore.DbMigrations.Migrations
{
    [DbContext(typeof(ObjectMigrationsDbContext))]
    [Migration("20200825022122_DbSchema")]
    partial class DbSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Object.Domain.Smkt.Info050", b =>
                {
                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Bmdm")
                        .HasColumnName("bmdm")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Bp")
                        .HasColumnName("bp")
                        .HasColumnType("varchar(24)")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Bz")
                        .HasColumnName("bz")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("CompHz")
                        .HasColumnName("comp_hz")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("CompName")
                        .HasColumnName("comp_name")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("CompType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("comp_type")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("CwCompId")
                        .HasColumnName("cw_comp_id")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("CwCompName")
                        .HasColumnName("cw_comp_name")
                        .HasColumnType("varchar(140)")
                        .HasMaxLength(140)
                        .IsUnicode(false);

                    b.Property<string>("Cz")
                        .HasColumnName("cz")
                        .HasColumnType("varchar(24)")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Dh1")
                        .HasColumnName("dh1")
                        .HasColumnType("varchar(24)")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Dh2")
                        .HasColumnName("dh2")
                        .HasColumnType("varchar(24)")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Dh3")
                        .HasColumnName("dh3")
                        .HasColumnType("varchar(24)")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Dlzt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dlzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Dz")
                        .HasColumnName("dz")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(24)")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Filemark")
                        .HasColumnName("filemark")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("FtpPassword")
                        .HasColumnName("ftp_password")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("FtpRevfilePath")
                        .HasColumnName("ftp_revfile_path")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("FtpSendfilePath")
                        .HasColumnName("ftp_sendfile_path")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("FtpServer")
                        .HasColumnName("ftp_server")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("FtpTimeOut")
                        .HasColumnName("ftp_time_out")
                        .HasColumnType("int");

                    b.Property<string>("FtpUser")
                        .HasColumnName("ftp_user")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Lx")
                        .IsRequired()
                        .HasColumnName("lx")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Lxr")
                        .HasColumnName("lxr")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal?>("Mj")
                        .HasColumnName("mj")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<int?>("Pos")
                        .HasColumnName("pos")
                        .HasColumnType("int");

                    b.Property<decimal>("Pszk")
                        .HasColumnName("pszk")
                        .HasColumnType("numeric(5, 2)");

                    b.Property<string>("Sjdj")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sjdj")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("UpComp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("up_comp")
                        .HasColumnType("char(6)")
                        .HasDefaultValueSql("('999999')")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Warehouseid")
                        .HasColumnName("warehouseid")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Yzbm")
                        .HasColumnName("yzbm")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Zxjg")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zxjg")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('1')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("CompId")
                        .HasName("info050_0");

                    b.ToTable("info050","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info107", b =>
                {
                    b.Property<string>("Rydm")
                        .HasColumnName("rydm")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Dlzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dlzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("ExtKl")
                        .HasColumnName("ext_kl")
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Kl")
                        .HasColumnName("kl")
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Qx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qx")
                        .HasColumnType("varchar(60)")
                        .HasDefaultValueSql("('000000000000000000000000000000000000000000000000000000000000')")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Ryjb")
                        .IsRequired()
                        .HasColumnName("ryjb")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Rymc")
                        .IsRequired()
                        .HasColumnName("rymc")
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<string>("Ryzw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ryzw")
                        .HasColumnType("varchar(4)")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Xzdm")
                        .IsRequired()
                        .HasColumnName("xzdm")
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.HasKey("Rydm")
                        .HasName("info107_0");

                    b.ToTable("info107","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info200", b =>
                {
                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<int>("AqkcTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("aqkc_ts")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((3))");

                    b.Property<string>("Bmdm")
                        .IsRequired()
                        .HasColumnName("bmdm")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Bz")
                        .HasColumnName("bz")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<decimal>("Bzl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bzl")
                        .HasColumnType("numeric(8, 2)")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Bzlbz")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bzlbz")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<short?>("Bzq")
                        .HasColumnName("bzq")
                        .HasColumnType("smallint");

                    b.Property<string>("CSpdm")
                        .HasColumnName("c_spdm")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Ccfs")
                        .HasColumnName("ccfs")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Ccsm")
                        .HasColumnName("ccsm")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Cd")
                        .HasColumnName("cd")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ChangeAbc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("change_abc")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("CwFlbh")
                        .HasColumnName("cw_flbh")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Dhxs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dhxs")
                        .HasColumnType("numeric(5, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<string>("Dldm")
                        .IsRequired()
                        .HasColumnName("dldm")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Dw1")
                        .HasColumnName("dw1")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Dw2")
                        .IsRequired()
                        .HasColumnName("dw2")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Flag")
                        .HasColumnName("flag")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Flag1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("flag1")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Flag2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("flag2")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("FlagCb")
                        .HasColumnName("flag_cb")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Ggxh")
                        .HasColumnName("ggxh")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Ghfdm")
                        .IsRequired()
                        .HasColumnName("ghfdm")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("IsJksp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_jksp")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("IsNcp")
                        .HasColumnName("is_ncp")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Jhfs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("jhfs")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('1')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Jhsj")
                        .HasColumnName("jhsj")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("KcsxTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("kcsx_ts")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((90))");

                    b.Property<int>("KcxxTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("kcxx_ts")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("MinDhsl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("min_dhsl")
                        .HasColumnType("numeric(12, 3)")
                        .HasDefaultValueSql("((0.000))");

                    b.Property<decimal>("PmkcSl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pmkc_sl")
                        .HasColumnType("numeric(12, 3)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<string>("Ppdm")
                        .HasColumnName("ppdm")
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Qysj")
                        .HasColumnName("qysj")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Sb")
                        .HasColumnName("sb")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<decimal>("Sl")
                        .HasColumnName("sl")
                        .HasColumnType("numeric(5, 2)");

                    b.Property<string>("SpAbc")
                        .HasColumnName("sp_abc")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("SpAbc1")
                        .HasColumnName("sp_abc1")
                        .HasColumnType("char(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("SpHz")
                        .HasColumnName("sp_hz")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Spmc")
                        .IsRequired()
                        .HasColumnName("spmc")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<string>("Sptm")
                        .IsRequired()
                        .HasColumnName("sptm")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Spxz")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spxz")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Spzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Spzt1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spzt1")
                        .HasColumnType("char(2)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Ttsj")
                        .HasColumnName("ttsj")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Xh")
                        .HasColumnName("xh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int?>("Xhqc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("xhqc")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Xkc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("xkc")
                        .HasColumnType("numeric(12, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<string>("Xldm")
                        .IsRequired()
                        .HasColumnName("xldm")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Xslb")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("xslb")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Xzdm")
                        .IsRequired()
                        .HasColumnName("xzdm")
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("ZbFlag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zb_flag")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Zdtm")
                        .HasColumnName("zdtm")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Zjm")
                        .HasColumnName("zjm")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Zldm")
                        .IsRequired()
                        .HasColumnName("zldm")
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<int>("Zpsl")
                        .HasColumnName("zpsl")
                        .HasColumnType("int");

                    b.Property<int>("Zptj")
                        .HasColumnName("zptj")
                        .HasColumnType("int");

                    b.HasKey("CompId", "Spdm")
                        .HasName("info200_0");

                    b.ToTable("info200","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info201", b =>
                {
                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<decimal>("Cxhysj")
                        .HasColumnName("cxhysj")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Cxjj")
                        .HasColumnName("cxjj")
                        .HasColumnType("numeric(11, 4)");

                    b.Property<DateTime?>("Cxjjsj")
                        .HasColumnName("cxjjsj")
                        .HasColumnType("smalldatetime");

                    b.Property<decimal>("Cxsj")
                        .HasColumnName("cxsj")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Cxzk")
                        .HasColumnName("cxzk")
                        .HasColumnType("numeric(5, 2)");

                    b.Property<decimal>("Cxzxj")
                        .HasColumnName("cxzxj")
                        .HasColumnType("numeric(9, 4)");

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Flag")
                        .HasColumnName("flag")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal>("Ghfzk")
                        .HasColumnName("ghfzk")
                        .HasColumnType("numeric(5, 2)");

                    b.Property<decimal>("Hysj")
                        .HasColumnName("hysj")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Jfbl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("jfbl")
                        .HasColumnType("numeric(5, 2)")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("Jj")
                        .HasColumnName("jj")
                        .HasColumnType("numeric(11, 4)");

                    b.Property<decimal>("Jjl")
                        .HasColumnName("jjl")
                        .HasColumnType("numeric(5, 2)");

                    b.Property<DateTime?>("Jjzzsj")
                        .HasColumnName("jjzzsj")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Lscxhysj")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lscxhysj")
                        .HasColumnType("numeric(9, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<decimal>("Lscxjj")
                        .HasColumnName("lscxjj")
                        .HasColumnType("numeric(18, 7)");

                    b.Property<decimal>("Lscxkl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lscxkl")
                        .HasColumnType("numeric(7, 4)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<decimal>("Lscxsj")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lscxsj")
                        .HasColumnType("numeric(9, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<decimal>("Lscxzk")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lscxzk")
                        .HasColumnType("numeric(5, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<decimal>("Lscxzxj")
                        .HasColumnName("lscxzxj")
                        .HasColumnType("numeric(9, 4)");

                    b.Property<DateTime?>("Lsjjqs")
                        .HasColumnName("lsjjqs")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("Lsjjzz")
                        .HasColumnName("lsjjzz")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("Lsqssj")
                        .HasColumnName("lsqssj")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("Lszzsj")
                        .HasColumnName("lszzsj")
                        .HasColumnType("smalldatetime");

                    b.Property<decimal>("Psj1")
                        .HasColumnName("psj1")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Psj2")
                        .HasColumnName("psj2")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Psj3")
                        .HasColumnName("psj3")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<DateTime?>("Qssj")
                        .HasColumnName("qssj")
                        .HasColumnType("smalldatetime");

                    b.Property<decimal>("Sj")
                        .HasColumnName("sj")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<string>("Spzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spzt")
                        .HasColumnType("char(2)")
                        .HasDefaultValueSql("('00')")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TransDate")
                        .HasColumnName("trans_date")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("TransReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trans_reason")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("TransState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trans_state")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal>("Zk")
                        .HasColumnName("zk")
                        .HasColumnType("numeric(5, 2)");

                    b.Property<decimal>("Zxj")
                        .HasColumnName("zxj")
                        .HasColumnType("numeric(11, 4)");

                    b.Property<DateTime?>("Zzsj")
                        .HasColumnName("zzsj")
                        .HasColumnType("smalldatetime");

                    b.HasKey("CompId", "Spdm")
                        .HasName("info201_0");

                    b.ToTable("info201","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info216", b =>
                {
                    b.Property<string>("Kbdm")
                        .HasColumnName("kbdm")
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("CompId")
                        .IsRequired()
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Kbmc")
                        .IsRequired()
                        .HasColumnName("kbmc")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Kbtm")
                        .IsRequired()
                        .HasColumnName("kbtm")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Qysj")
                        .HasColumnName("qysj")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Spzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Ttsj")
                        .HasColumnName("ttsj")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Kbdm")
                        .HasName("info216_0");

                    b.ToTable("info216","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info217", b =>
                {
                    b.Property<string>("Kbdm")
                        .HasColumnName("kbdm")
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("CompId")
                        .IsRequired()
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<decimal>("Cxhysj")
                        .HasColumnName("cxhysj")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Cxsj")
                        .HasColumnName("cxsj")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<DateTime>("Firstdate")
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Hysj")
                        .HasColumnName("hysj")
                        .HasColumnType("numeric(13, 6)");

                    b.Property<decimal>("Kbsl")
                        .HasColumnName("kbsl")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<DateTime>("Lastdate")
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Sj")
                        .HasColumnName("sj")
                        .HasColumnType("numeric(13, 6)");

                    b.HasKey("Kbdm", "Spdm")
                        .HasName("info217_0");

                    b.ToTable("info217","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info223", b =>
                {
                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Sptm")
                        .HasColumnName("sptm")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Bz")
                        .HasColumnName("bz")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Zdtm")
                        .HasColumnName("zdtm")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.HasKey("CompId", "Spdm", "Sptm")
                        .HasName("info223_0")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("info223","smkt");
                });
#pragma warning restore 612, 618
        }
    }
}
