// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Object.EntityFrameworkCore.DbMigrations;
using Volo.Abp.EntityFrameworkCore;

namespace Object.EntityFrameworkCore.DbMigrations.Migrations
{
    [DbContext(typeof(ObjectMigrationsDbContext))]
    [Migration("20200828021100_order")]
    partial class order
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Object.Domain.Smkt.Info050", b =>
                {
                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasComment("门店代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Bmdm")
                        .HasColumnName("bmdm")
                        .HasColumnType("varchar(2)")
                        .HasComment("部门代码")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Bp")
                        .HasColumnName("bp")
                        .HasColumnType("varchar(24)")
                        .HasComment("BP机号")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Bz")
                        .HasColumnName("bz")
                        .HasColumnType("varchar(255)")
                        .HasComment("备注")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("varchar(6)")
                        .HasComment("体系代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("CompHz")
                        .HasColumnName("comp_hz")
                        .HasColumnType("varchar(15)")
                        .HasComment("货主")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("CompName")
                        .HasColumnName("comp_name")
                        .HasColumnType("varchar(200)")
                        .HasComment("门店名称")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("CompType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("comp_type")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("门店类型")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("CwCompId")
                        .HasColumnName("cw_comp_id")
                        .HasColumnType("varchar(30)")
                        .HasComment("第三方代码")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("CwCompName")
                        .HasColumnName("cw_comp_name")
                        .HasColumnType("varchar(140)")
                        .HasComment("第三方名称")
                        .HasMaxLength(140)
                        .IsUnicode(false);

                    b.Property<string>("Cz")
                        .HasColumnName("cz")
                        .HasColumnType("varchar(24)")
                        .HasComment("传真")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Dh1")
                        .HasColumnName("dh1")
                        .HasColumnType("varchar(24)")
                        .HasComment("电话1")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Dh2")
                        .HasColumnName("dh2")
                        .HasColumnType("varchar(24)")
                        .HasComment("电话2")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Dh3")
                        .HasColumnName("dh3")
                        .HasColumnType("varchar(24)")
                        .HasComment("电话3")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Dlzt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dlzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("登录状态")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Dz")
                        .HasColumnName("dz")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(24)")
                        .HasComment("邮箱")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Filemark")
                        .HasColumnName("filemark")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("组织类型")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("创建人");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasComment("创建时间")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("FtpPassword")
                        .HasColumnName("ftp_password")
                        .HasColumnType("varchar(20)")
                        .HasComment("ftp密码")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("FtpRevfilePath")
                        .HasColumnName("ftp_revfile_path")
                        .HasColumnType("varchar(30)")
                        .HasComment("ftp接收该单位文件路径")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("FtpSendfilePath")
                        .HasColumnName("ftp_sendfile_path")
                        .HasColumnType("varchar(30)")
                        .HasComment("ftp发送该单位文件路径")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("FtpServer")
                        .HasColumnName("ftp_server")
                        .HasColumnType("varchar(30)")
                        .HasComment("ftp服务器")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("FtpTimeOut")
                        .HasColumnName("ftp_time_out")
                        .HasColumnType("int")
                        .HasComment("ftp连接超时设置");

                    b.Property<string>("FtpUser")
                        .HasColumnName("ftp_user")
                        .HasColumnType("varchar(20)")
                        .HasComment("ftp用户名")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("修改时间");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasComment("修改人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Lx")
                        .IsRequired()
                        .HasColumnName("lx")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("店类型")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Lxr")
                        .HasColumnName("lxr")
                        .HasColumnType("varchar(10)")
                        .HasComment("联系人")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal?>("Mj")
                        .HasColumnName("mj")
                        .HasColumnType("numeric(12, 2)")
                        .HasComment("店面面积");

                    b.Property<int?>("Pos")
                        .HasColumnName("pos")
                        .HasColumnType("int")
                        .HasComment("Pos机台数");

                    b.Property<decimal>("Pszk")
                        .HasColumnName("pszk")
                        .HasColumnType("numeric(5, 2)")
                        .HasComment("配送折扣");

                    b.Property<string>("Sjdj")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sjdj")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("是否显示进价")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("UpComp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("up_comp")
                        .HasColumnType("char(6)")
                        .HasDefaultValueSql("('999999')")
                        .IsFixedLength(true)
                        .HasComment("上级店代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Warehouseid")
                        .HasColumnName("warehouseid")
                        .HasColumnType("varchar(30)")
                        .HasComment("配送仓库")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Yzbm")
                        .HasColumnName("yzbm")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasComment("邮政编码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Zxjg")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zxjg")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('1')")
                        .IsFixedLength(true)
                        .HasComment("执行价格")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("CompId")
                        .HasName("info050_0");

                    b.ToTable("info050","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info107", b =>
                {
                    b.Property<string>("Rydm")
                        .HasColumnName("rydm")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("人员代码")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasComment("门店代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Dlzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dlzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("登录状态")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("ExtKl")
                        .HasColumnName("ext_kl")
                        .HasColumnType("varchar(8)")
                        .HasComment("人员口令(app)")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("创建时间");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasComment("创建人员")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Kl")
                        .HasColumnName("kl")
                        .HasColumnType("varchar(8)")
                        .HasComment("人员口令(前台)")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("修改时间");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasComment("修改人员")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Qx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qx")
                        .HasColumnType("varchar(60)")
                        .HasDefaultValueSql("('000000000000000000000000000000000000000000000000000000000000')")
                        .HasComment("人员权限")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Ryjb")
                        .IsRequired()
                        .HasColumnName("ryjb")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("人员级别")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Rymc")
                        .IsRequired()
                        .HasColumnName("rymc")
                        .HasColumnType("varchar(16)")
                        .HasComment("人员名称")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<string>("Ryzw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ryzw")
                        .HasColumnType("varchar(4)")
                        .HasDefaultValueSql("('')")
                        .HasComment("人员职位")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Xzdm")
                        .IsRequired()
                        .HasColumnName("xzdm")
                        .HasColumnType("varchar(4)")
                        .HasComment("小组代码")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.HasKey("Rydm")
                        .HasName("info107_0");

                    b.ToTable("info107","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info200", b =>
                {
                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("nvarchar(8)")
                        .HasComment("门店代码")
                        .HasMaxLength(8);

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasComment("商品代码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<int>("AqkcTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("aqkc_ts")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((3))")
                        .HasComment("安全库存天数");

                    b.Property<string>("Bmdm")
                        .IsRequired()
                        .HasColumnName("bmdm")
                        .HasColumnType("varchar(2)")
                        .HasComment("部门代码")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Bz")
                        .HasColumnName("bz")
                        .HasColumnType("varchar(64)")
                        .HasComment("备注")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<decimal>("Bzl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bzl")
                        .HasColumnType("numeric(8, 2)")
                        .HasDefaultValueSql("((1))")
                        .HasComment("包装率");

                    b.Property<string>("Bzlbz")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bzlbz")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("包装率标志")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<short?>("Bzq")
                        .HasColumnName("bzq")
                        .HasColumnType("smallint")
                        .HasComment("保质期");

                    b.Property<string>("CSpdm")
                        .HasColumnName("c_spdm")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("第三方货号")
                        .HasMaxLength(20);

                    b.Property<string>("Ccfs")
                        .HasColumnName("ccfs")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("存储方式")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Ccsm")
                        .HasColumnName("ccsm")
                        .HasColumnType("varchar(255)")
                        .HasComment("存储说明")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Cd")
                        .HasColumnName("cd")
                        .HasColumnType("varchar(50)")
                        .HasComment("产地")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ChangeAbc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("change_abc")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("CwFlbh")
                        .HasColumnName("cw_flbh")
                        .HasColumnType("varchar(50)")
                        .HasComment("税收分类")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Dhxs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dhxs")
                        .HasColumnType("numeric(5, 2)")
                        .HasDefaultValueSql("((0.00))")
                        .HasComment("订货销售");

                    b.Property<string>("Dldm")
                        .IsRequired()
                        .HasColumnName("dldm")
                        .HasColumnType("varchar(2)")
                        .HasComment("大类代码")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Dw1")
                        .HasColumnName("dw1")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("整单位")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Dw2")
                        .IsRequired()
                        .HasColumnName("dw2")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("零单位")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("创建时间");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("创建人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Flag")
                        .HasColumnName("flag")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("整订标志")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Flag1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("flag1")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("联营标志")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Flag2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("flag2")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("生鲜标志")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("FlagCb")
                        .HasColumnName("flag_cb")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("是否拆包")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Ggxh")
                        .HasColumnName("ggxh")
                        .HasColumnType("varchar(50)")
                        .HasComment("供货方代码")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Ghfdm")
                        .IsRequired()
                        .HasColumnName("ghfdm")
                        .HasColumnType("varchar(6)")
                        .HasComment("供货方序号")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("IsJksp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_jksp")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("是否进口商品")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("IsNcp")
                        .HasColumnName("is_ncp")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("是否农商品")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Jhfs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("jhfs")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('1')")
                        .IsFixedLength(true)
                        .HasComment("进货方式")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Jhsj")
                        .HasColumnName("jhsj")
                        .HasColumnType("smalldatetime")
                        .HasComment("首次进货时间");

                    b.Property<int>("KcsxTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("kcsx_ts")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((90))");

                    b.Property<int>("KcxxTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("kcxx_ts")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))")
                        .HasComment("库存下限天数");

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("修改时间");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("修改人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("MinDhsl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("min_dhsl")
                        .HasColumnType("numeric(12, 3)")
                        .HasDefaultValueSql("((0.000))")
                        .HasComment("最小订货量");

                    b.Property<decimal>("PmkcSl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pmkc_sl")
                        .HasColumnType("numeric(12, 3)")
                        .HasDefaultValueSql("((0.00))")
                        .HasComment("排面库存数量");

                    b.Property<string>("Ppdm")
                        .HasColumnName("ppdm")
                        .HasColumnType("varchar(4)")
                        .HasComment("品牌代码")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Qysj")
                        .HasColumnName("qysj")
                        .HasColumnType("smalldatetime")
                        .HasComment("起用时间");

                    b.Property<string>("Sb")
                        .HasColumnName("sb")
                        .HasColumnType("varchar(20)")
                        .HasComment("商标")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<decimal>("Sl")
                        .HasColumnName("sl")
                        .HasColumnType("numeric(5, 2)")
                        .HasComment("税率");

                    b.Property<string>("SpAbc")
                        .HasColumnName("sp_abc")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("商品ABC")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("SpAbc1")
                        .HasColumnName("sp_abc1")
                        .HasColumnType("char(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("SpHz")
                        .HasColumnName("sp_hz")
                        .HasColumnType("varchar(50)")
                        .HasComment("货主")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Spmc")
                        .IsRequired()
                        .HasColumnName("spmc")
                        .HasColumnType("varchar(64)")
                        .HasComment("商品名称")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<string>("Sptm")
                        .IsRequired()
                        .HasColumnName("sptm")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasComment("店内条码")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Spxz")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spxz")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("电子秤商品标志")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Spzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("商品状态")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Spzt1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spzt1")
                        .HasColumnType("char(2)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Ttsj")
                        .HasColumnName("ttsj")
                        .HasColumnType("smalldatetime")
                        .HasComment("终止/淘汰时间");

                    b.Property<string>("Xh")
                        .HasColumnName("xh")
                        .HasColumnType("varchar(3)")
                        .HasComment("供货方序号")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int?>("Xhqc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("xhqc")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))")
                        .HasComment("消耗期长");

                    b.Property<decimal?>("Xkc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("xkc")
                        .HasColumnType("numeric(12, 2)")
                        .HasDefaultValueSql("((0.00))")
                        .HasComment("虚库存");

                    b.Property<string>("Xldm")
                        .IsRequired()
                        .HasColumnName("xldm")
                        .HasColumnType("varchar(6)")
                        .HasComment("小类代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Xslb")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("xslb")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("部门销售标志")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Xzdm")
                        .IsRequired()
                        .HasColumnName("xzdm")
                        .HasColumnType("varchar(4)")
                        .HasComment("小组代码")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("ZbFlag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zb_flag")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("整订标志")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Zdtm")
                        .HasColumnName("zdtm")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasComment("自带条码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Zjm")
                        .HasColumnName("zjm")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("助记码")
                        .HasMaxLength(20);

                    b.Property<string>("Zldm")
                        .IsRequired()
                        .HasColumnName("zldm")
                        .HasColumnType("varchar(4)")
                        .HasComment("中类代码")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<int>("Zpsl")
                        .HasColumnName("zpsl")
                        .HasColumnType("int")
                        .HasComment("赠品数量");

                    b.Property<int>("Zptj")
                        .HasColumnName("zptj")
                        .HasColumnType("int")
                        .HasComment("赠品条件");

                    b.HasKey("CompId", "Spdm")
                        .HasName("info200_0");

                    b.ToTable("info200","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info201", b =>
                {
                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasComment("门店代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasComment("商品代码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<decimal>("Cxhysj")
                        .HasColumnName("cxhysj")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("促销会员售价");

                    b.Property<decimal>("Cxjj")
                        .HasColumnName("cxjj")
                        .HasColumnType("numeric(11, 4)")
                        .HasComment("促销含税进价");

                    b.Property<DateTime?>("Cxjjsj")
                        .HasColumnName("cxjjsj")
                        .HasColumnType("smalldatetime")
                        .HasComment("促销进价起始时间");

                    b.Property<decimal>("Cxsj")
                        .HasColumnName("cxsj")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("促销售价");

                    b.Property<decimal>("Cxzk")
                        .HasColumnName("cxzk")
                        .HasColumnType("numeric(5, 2)")
                        .HasComment("促销折扣");

                    b.Property<decimal>("Cxzxj")
                        .HasColumnName("cxzxj")
                        .HasColumnType("numeric(9, 4)")
                        .HasComment("促销整箱价");

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("创建时间");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("创建人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Flag")
                        .HasColumnName("flag")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal>("Ghfzk")
                        .HasColumnName("ghfzk")
                        .HasColumnType("numeric(5, 2)")
                        .HasComment("供货方折扣");

                    b.Property<decimal>("Hysj")
                        .HasColumnName("hysj")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("会员售价");

                    b.Property<decimal>("Jfbl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("jfbl")
                        .HasColumnType("numeric(5, 2)")
                        .HasDefaultValueSql("((1))")
                        .HasComment("积分比例");

                    b.Property<decimal>("Jj")
                        .HasColumnName("jj")
                        .HasColumnType("numeric(11, 4)")
                        .HasComment("含税进价");

                    b.Property<decimal>("Jjl")
                        .HasColumnName("jjl")
                        .HasColumnType("numeric(5, 2)")
                        .HasComment("加价率");

                    b.Property<DateTime?>("Jjzzsj")
                        .HasColumnName("jjzzsj")
                        .HasColumnType("smalldatetime")
                        .HasComment("促销进价终止时间");

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("修改时间");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("修改人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Lscxhysj")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lscxhysj")
                        .HasColumnType("numeric(9, 2)")
                        .HasDefaultValueSql("((0.00))")
                        .HasComment("历史促销会员售价");

                    b.Property<decimal>("Lscxjj")
                        .HasColumnName("lscxjj")
                        .HasColumnType("numeric(18, 7)")
                        .HasComment("历史促销含税进价");

                    b.Property<decimal>("Lscxkl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lscxkl")
                        .HasColumnType("numeric(7, 4)")
                        .HasDefaultValueSql("((0.00))")
                        .HasComment("历史促销扣率");

                    b.Property<decimal>("Lscxsj")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lscxsj")
                        .HasColumnType("numeric(9, 2)")
                        .HasDefaultValueSql("((0.00))")
                        .HasComment("历史促销售价");

                    b.Property<decimal>("Lscxzk")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lscxzk")
                        .HasColumnType("numeric(5, 2)")
                        .HasDefaultValueSql("((0.00))")
                        .HasComment("历史促销折扣");

                    b.Property<decimal>("Lscxzxj")
                        .HasColumnName("lscxzxj")
                        .HasColumnType("numeric(9, 4)")
                        .HasComment("历史促销整箱价");

                    b.Property<DateTime?>("Lsjjqs")
                        .HasColumnName("lsjjqs")
                        .HasColumnType("smalldatetime")
                        .HasComment("历史促销进价起始时间");

                    b.Property<DateTime?>("Lsjjzz")
                        .HasColumnName("lsjjzz")
                        .HasColumnType("smalldatetime")
                        .HasComment("历史促销进价终止时间");

                    b.Property<DateTime?>("Lsqssj")
                        .HasColumnName("lsqssj")
                        .HasColumnType("smalldatetime")
                        .HasComment("历史促销售价起始时间");

                    b.Property<DateTime?>("Lszzsj")
                        .HasColumnName("lszzsj")
                        .HasColumnType("smalldatetime")
                        .HasComment("历史促销售价终止时间");

                    b.Property<decimal>("Psj1")
                        .HasColumnName("psj1")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("配送价一");

                    b.Property<decimal>("Psj2")
                        .HasColumnName("psj2")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("配送价二");

                    b.Property<decimal>("Psj3")
                        .HasColumnName("psj3")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("配送价三");

                    b.Property<DateTime?>("Qssj")
                        .HasColumnName("qssj")
                        .HasColumnType("smalldatetime")
                        .HasComment("促销售价起始时间");

                    b.Property<decimal>("Sj")
                        .HasColumnName("sj")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("售价");

                    b.Property<string>("Spzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spzt")
                        .HasColumnType("char(2)")
                        .HasDefaultValueSql("('00')")
                        .IsFixedLength(true)
                        .HasComment("商品状态")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TransDate")
                        .HasColumnName("trans_date")
                        .HasColumnType("smalldatetime")
                        .HasComment("传输时间");

                    b.Property<string>("TransReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trans_reason")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("传输原因")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("TransState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trans_state")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("传输状态")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal>("Zk")
                        .HasColumnName("zk")
                        .HasColumnType("numeric(5, 2)")
                        .HasComment("折扣");

                    b.Property<decimal>("Zxj")
                        .HasColumnName("zxj")
                        .HasColumnType("numeric(11, 4)")
                        .HasComment("整箱价");

                    b.Property<DateTime?>("Zzsj")
                        .HasColumnName("zzsj")
                        .HasColumnType("smalldatetime")
                        .HasComment("促销售价终止时间");

                    b.HasKey("CompId", "Spdm")
                        .HasName("info201_0");

                    b.ToTable("info201","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info216", b =>
                {
                    b.Property<string>("Kbdm")
                        .HasColumnName("kbdm")
                        .HasColumnType("varchar(13)")
                        .HasComment("捆绑代码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("CompId")
                        .IsRequired()
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasComment("门店代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("创建时间");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("创建人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Kbmc")
                        .IsRequired()
                        .HasColumnName("kbmc")
                        .HasColumnType("varchar(40)")
                        .HasComment("捆绑名称")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Kbtm")
                        .IsRequired()
                        .HasColumnName("kbtm")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasComment("捆绑条码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("修改时间");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("修改人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Qysj")
                        .HasColumnName("qysj")
                        .HasColumnType("smalldatetime")
                        .HasComment("起用时间");

                    b.Property<string>("Spzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("spzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasComment("商品状态")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Ttsj")
                        .HasColumnName("ttsj")
                        .HasColumnType("smalldatetime")
                        .HasComment("淘汰时间");

                    b.HasKey("Kbdm")
                        .HasName("info216_0");

                    b.ToTable("info216","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info217", b =>
                {
                    b.Property<string>("Kbdm")
                        .HasColumnName("kbdm")
                        .HasColumnType("varchar(13)")
                        .HasComment("捆绑代码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasComment("商品代码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("CompId")
                        .IsRequired()
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasComment("门店代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<decimal>("Cxhysj")
                        .HasColumnName("cxhysj")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("促销会员售价");

                    b.Property<decimal>("Cxsj")
                        .HasColumnName("cxsj")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("促销售价");

                    b.Property<DateTime>("Firstdate")
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasComment("创建时间");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("创建人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Hysj")
                        .HasColumnName("hysj")
                        .HasColumnType("numeric(13, 6)")
                        .HasComment("会员售价");

                    b.Property<decimal>("Kbsl")
                        .HasColumnName("kbsl")
                        .HasColumnType("numeric(9, 2)")
                        .HasComment("捆绑售价");

                    b.Property<DateTime>("Lastdate")
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasComment("修改时间");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("修改人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Sj")
                        .HasColumnName("sj")
                        .HasColumnType("numeric(13, 6)")
                        .HasComment("售价");

                    b.HasKey("Kbdm", "Spdm")
                        .HasName("info217_0");

                    b.ToTable("info217","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info223", b =>
                {
                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasComment("门店代码")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasComment("商品代码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Sptm")
                        .HasColumnName("sptm")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasComment("店内条码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<string>("Bz")
                        .HasColumnName("bz")
                        .HasColumnType("varchar(64)")
                        .HasComment("备注")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasComment("创建时间");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("创建人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasComment("修改时间");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasComment("修改人")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Zdtm")
                        .HasColumnName("zdtm")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasComment("自带条码")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.HasKey("CompId", "Spdm", "Sptm")
                        .HasName("info223_0")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("info223","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Info702", b =>
                {
                    b.Property<string>("Bzdm")
                        .HasColumnName("bzdm")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Bshbz")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bshbz")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Bzlx")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bzlx")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Bzmc")
                        .IsRequired()
                        .HasColumnName("bzmc")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("BzmcE")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bzmc_e")
                        .HasColumnType("char(8)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength(true)
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("Dlzt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dlzt")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("Firstdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Firstman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("firstman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Fkzddw")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("fkzddw")
                        .HasColumnType("numeric(9, 2)")
                        .HasDefaultValueSql("((100))");

                    b.Property<decimal>("Fkzxdw")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("fkzxdw")
                        .HasColumnType("numeric(9, 2)")
                        .HasDefaultValueSql("((0.01))");

                    b.Property<decimal>("Hl")
                        .HasColumnName("hl")
                        .HasColumnType("numeric(18, 7)");

                    b.Property<string>("Hotkey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("hotkey")
                        .HasColumnType("char(2)")
                        .HasDefaultValueSql("('00')")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime>("Lastdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastdate")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Lastman")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lastman")
                        .HasColumnType("char(4)")
                        .HasDefaultValueSql("('9999')")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Qtsybz")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qtsybz")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('1')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sqhbz")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sqhbz")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Zlbz")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zlbz")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("Bzdm")
                        .HasName("info702_0");

                    b.ToTable("info702","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Smkt140", b =>
                {
                    b.Property<string>("Jyh")
                        .HasColumnName("jyh")
                        .HasColumnType("char(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<string>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("flag")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Clsj")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("clsj")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CompId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .HasDefaultValueSql("('000005')")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<decimal?>("Fkfs1")
                        .HasColumnName("fkfs1")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Fkfs2")
                        .HasColumnName("fkfs2")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Fkfs3")
                        .HasColumnName("fkfs3")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Fkfs4")
                        .HasColumnName("fkfs4")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Fkfs5")
                        .HasColumnName("fkfs5")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Fkfs6")
                        .HasColumnName("fkfs6")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Fkfs7")
                        .HasColumnName("fkfs7")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Fkfs8")
                        .HasColumnName("fkfs8")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Gnqje")
                        .HasColumnName("gnqje")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<string>("Hybh")
                        .HasColumnName("hybh")
                        .HasColumnType("char(13)")
                        .IsFixedLength(true)
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<decimal?>("Hyk")
                        .HasColumnName("hyk")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Hyyh")
                        .HasColumnName("hyyh")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Je1")
                        .HasColumnName("je1")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Je2")
                        .HasColumnName("je2")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Je3")
                        .HasColumnName("je3")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<DateTime>("Jysj")
                        .HasColumnName("jysj")
                        .HasColumnType("smalldatetime");

                    b.Property<decimal?>("Lmkye")
                        .HasColumnName("lmkye")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<string>("Skjh")
                        .IsRequired()
                        .HasColumnName("skjh")
                        .HasColumnType("char(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Skydm")
                        .IsRequired()
                        .HasColumnName("skydm")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Ssje")
                        .HasColumnName("ssje")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Xj")
                        .HasColumnName("xj")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Xyk")
                        .HasColumnName("xyk")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Yhje")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("yhje")
                        .HasColumnType("numeric(10, 2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Yhxyk")
                        .HasColumnName("yhxyk")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<string>("YhxykNo")
                        .HasColumnName("yhxyk_no")
                        .HasColumnType("char(20)")
                        .IsFixedLength(true)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Yhxyklx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("yhxyklx")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Yyydm")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("yyydm")
                        .HasColumnType("char(10)")
                        .HasDefaultValueSql("(space((10)))")
                        .IsFixedLength(true)
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal>("Zje")
                        .HasColumnName("zje")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Zkje")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zkje")
                        .HasColumnType("numeric(10, 2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Zlczje")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zlczje")
                        .HasColumnType("numeric(12, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<decimal?>("Zlje")
                        .HasColumnName("zlje")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Zlyh")
                        .HasColumnName("zlyh")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Zp")
                        .HasColumnName("zp")
                        .HasColumnType("numeric(10, 2)");

                    b.HasKey("Jyh", "Flag");

                    b.ToTable("smkt140","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Smkt141", b =>
                {
                    b.Property<string>("Jyh")
                        .HasColumnName("jyh")
                        .HasColumnType("char(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<string>("Jyflag")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("jyflag")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('0')")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("Sequ")
                        .HasColumnName("sequ")
                        .HasColumnType("int");

                    b.Property<string>("Spdm")
                        .HasColumnName("spdm")
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13)
                        .IsUnicode(false);

                    b.Property<decimal?>("Abcx")
                        .HasColumnName("abcx")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Bsyh")
                        .HasColumnName("bsyh")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Cxbz")
                        .HasColumnName("cxbz")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnName("flag")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal?>("Hyyh")
                        .HasColumnName("hyyh")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Jfbl")
                        .HasColumnName("jfbl")
                        .HasColumnType("numeric(5, 2)");

                    b.Property<DateTime>("Jysj")
                        .HasColumnName("jysj")
                        .HasColumnType("smalldatetime");

                    b.Property<decimal?>("Mmyh")
                        .HasColumnName("mmyh")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal?>("Mzyh")
                        .HasColumnName("mzyh")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Ssje")
                        .HasColumnName("ssje")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Xsdj")
                        .HasColumnName("xsdj")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<string>("Xsph")
                        .HasColumnName("xsph")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<decimal>("Xssl")
                        .HasColumnName("xssl")
                        .HasColumnType("numeric(9, 3)");

                    b.Property<decimal?>("Yhje")
                        .HasColumnName("yhje")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Ysje")
                        .HasColumnName("ysje")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<string>("Yyydm")
                        .HasColumnName("yyydm")
                        .HasColumnType("char(4)")
                        .IsFixedLength(true)
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal?>("Zkje")
                        .HasColumnName("zkje")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal?>("Zlyh")
                        .HasColumnName("zlyh")
                        .HasColumnType("numeric(12, 2)");

                    b.HasKey("Jyh", "Jyflag", "Sequ", "Spdm");

                    b.ToTable("smkt141","smkt");
                });

            modelBuilder.Entity("Object.Domain.Smkt.Smkt142", b =>
                {
                    b.Property<string>("Jyh")
                        .HasColumnName("jyh")
                        .HasColumnType("char(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<string>("Bzdm")
                        .HasColumnName("bzdm")
                        .HasColumnType("char(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("CompId")
                        .HasColumnName("comp_id")
                        .HasColumnType("char(6)")
                        .IsFixedLength(true)
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Jysj")
                        .HasColumnName("jysj")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Wzlje")
                        .HasColumnName("wzlje")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Ysje")
                        .HasColumnName("ysje")
                        .HasColumnType("numeric(12, 2)");

                    b.HasKey("Jyh", "Bzdm");

                    b.ToTable("smkt142","smkt");
                });
#pragma warning restore 612, 618
        }
    }
}
